# Generated by Django 4.2.6 on 2024-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_student_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
