# Generated by Django 4.2.6 on 2024-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_student_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
