# Generated by Django 4.2.6 on 2024-05-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.student",
            ),
        ),
    ]
