# Generated by Django 4.2.6 on 2024-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_parent_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="parent", name="admin",),
    ]
