# Generated by Django 4.2.6 on 2024-05-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_parent_admin_alter_parent_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.student",
            ),
        ),
    ]
