# Generated by Django 4.2.6 on 2024-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_feedbackparent"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="dept",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="mobile",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="qualification",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="subjects",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
