# Generated by Django 4.2.6 on 2024-05-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_staff_dept_staff_mobile_staff_qualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
