# Generated by Django 4.2.6 on 2024-06-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="marks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignments",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.staff",
            ),
        ),
    ]
