# Generated by Django 4.2.6 on 2024-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_assignments_marks_assignments_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignments",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
